#!/bin/bash

# Default container
CONTAINER="images/linger_v3.sif"

# If first argument doesn't start with -, treat it as container
[[ $# -ge 1 && $1 != -* ]] && CONTAINER=$1 && shift

# Default srun arguments
DEFAULT_SRUN_ARGS="-t 03:00:00 -N 1 -n 1 -c 16 --mem=64G --gres=gpu:0"

# Use remaining arguments if provided, else default
SRUN_ARGS=${@:-$DEFAULT_SRUN_ARGS}
#echo "$SRUN_ARGS"


echo "[JOB SUBMITTED] $(date)"

srun $SRUN_ARGS --pty bash -c '
    echo "[JOB STARTED]   $(date)"
    echo ""
    squeue --me
    echo ""

    # Run singularity + conda + jupyter-lab
    singularity exec --nv '"$CONTAINER"' bash -c "
        source /opt/conda/etc/profile.d/conda.sh && \
        conda activate LINGER && \
        jupyter-lab --ip \$(hostname -i | awk '\''{print \$NF}'\'')"
'

